/*
 * Student Tutor Booking Management System
 * This is a system allowing students and tutors to book in-person sessions at designated venues on campus.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 222641495@mycput.ac.za
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.StudentTutorBookingManagementSystem);
  }
}(this, function(expect, StudentTutorBookingManagementSystem) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('BookingDTO', function() {
      beforeEach(function() {
        instance = new StudentTutorBookingManagementSystem.BookingDTO();
      });

      it('should create an instance of BookingDTO', function() {
        // TODO: update the code to test BookingDTO
        expect(instance).to.be.a(StudentTutorBookingManagementSystem.BookingDTO);
      });

      it('should have the property bookingId (base name: "bookingId")', function() {
        // TODO: update the code to test the property bookingId
        expect(instance).to.have.property('bookingId');
        // expect(instance.bookingId).to.be(expectedValueLiteral);
      });

      it('should have the property tutorId (base name: "tutorId")', function() {
        // TODO: update the code to test the property tutorId
        expect(instance).to.have.property('tutorId');
        // expect(instance.tutorId).to.be(expectedValueLiteral);
      });

      it('should have the property studentId (base name: "studentId")', function() {
        // TODO: update the code to test the property studentId
        expect(instance).to.have.property('studentId');
        // expect(instance.studentId).to.be(expectedValueLiteral);
      });

      it('should have the property subjectId (base name: "subjectId")', function() {
        // TODO: update the code to test the property subjectId
        expect(instance).to.have.property('subjectId');
        // expect(instance.subjectId).to.be(expectedValueLiteral);
      });

      it('should have the property bookingDate (base name: "bookingDate")', function() {
        // TODO: update the code to test the property bookingDate
        expect(instance).to.have.property('bookingDate');
        // expect(instance.bookingDate).to.be(expectedValueLiteral);
      });

      it('should have the property startTime (base name: "startTime")', function() {
        // TODO: update the code to test the property startTime
        expect(instance).to.have.property('startTime');
        // expect(instance.startTime).to.be(expectedValueLiteral);
      });

      it('should have the property endTime (base name: "endTime")', function() {
        // TODO: update the code to test the property endTime
        expect(instance).to.have.property('endTime');
        // expect(instance.endTime).to.be(expectedValueLiteral);
      });

      it('should have the property locationId (base name: "locationId")', function() {
        // TODO: update the code to test the property locationId
        expect(instance).to.have.property('locationId');
        // expect(instance.locationId).to.be(expectedValueLiteral);
      });

      it('should have the property topic (base name: "topic")', function() {
        // TODO: update the code to test the property topic
        expect(instance).to.have.property('topic');
        // expect(instance.topic).to.be(expectedValueLiteral);
      });

    });
  });

}));
