/* tslint:disable */
/* eslint-disable */
/**
 * Student Tutor Booking Management System
 * This is a system allowing students and tutors to book in-person sessions at designated venues on campus.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 222641495@mycput.ac.za
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
export * from './apis/admin-api';
export * from './apis/booking-api';
export * from './apis/location-api';
export * from './apis/review-api';
export * from './apis/student-api';
export * from './apis/subject-api';
export * from './apis/tutor-api';

