/*
 * Student Tutor Booking Management System
 * This is a system allowing students and tutors to book in-person sessions at designated venues on campus.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 222641495@mycput.ac.za
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.61
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.StudentTutorBookingManagementSystem);
  }
}(this, function(expect, StudentTutorBookingManagementSystem) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('SubjectDTO', function() {
      beforeEach(function() {
        instance = new StudentTutorBookingManagementSystem.SubjectDTO();
      });

      it('should create an instance of SubjectDTO', function() {
        // TODO: update the code to test SubjectDTO
        expect(instance).to.be.a(StudentTutorBookingManagementSystem.SubjectDTO);
      });

      it('should have the property subjectId (base name: "subjectId")', function() {
        // TODO: update the code to test the property subjectId
        expect(instance).to.have.property('subjectId');
        // expect(instance.subjectId).to.be(expectedValueLiteral);
      });

      it('should have the property subjectCode (base name: "subjectCode")', function() {
        // TODO: update the code to test the property subjectCode
        expect(instance).to.have.property('subjectCode');
        // expect(instance.subjectCode).to.be(expectedValueLiteral);
      });

      it('should have the property subjectName (base name: "subjectName")', function() {
        // TODO: update the code to test the property subjectName
        expect(instance).to.have.property('subjectName');
        // expect(instance.subjectName).to.be(expectedValueLiteral);
      });

    });
  });

}));
