/*
 * Student Tutor Booking Management System
 * This is a system allowing students and tutors to book in-person sessions at designated venues on campus.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 222641495@mycput.ac.za
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The ReviewDTO model module.
 * @module model/ReviewDTO
 * @version 1.0.0
 */
export default class ReviewDTO {
  /**
   * Constructs a new <code>ReviewDTO</code>.
   * @alias module:model/ReviewDTO
   * @class
   * @param tutorId {Number} 
   * @param rating {Number} 
   * @param description {String} 
   * @param studentId {Number} 
   */
  constructor(tutorId, rating, description, studentId) {
    this.tutorId = tutorId;
    this.rating = rating;
    this.description = description;
    this.studentId = studentId;
  }

  /**
   * Constructs a <code>ReviewDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ReviewDTO} obj Optional instance to populate.
   * @return {module:model/ReviewDTO} The populated <code>ReviewDTO</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ReviewDTO();
      if (data.hasOwnProperty('reviewId'))
        obj.reviewId = ApiClient.convertToType(data['reviewId'], 'Number');
      if (data.hasOwnProperty('tutorId'))
        obj.tutorId = ApiClient.convertToType(data['tutorId'], 'Number');
      if (data.hasOwnProperty('rating'))
        obj.rating = ApiClient.convertToType(data['rating'], 'Number');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('studentId'))
        obj.studentId = ApiClient.convertToType(data['studentId'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} reviewId
 */
ReviewDTO.prototype.reviewId = undefined;

/**
 * @member {Number} tutorId
 */
ReviewDTO.prototype.tutorId = undefined;

/**
 * @member {Number} rating
 */
ReviewDTO.prototype.rating = undefined;

/**
 * @member {String} description
 */
ReviewDTO.prototype.description = undefined;

/**
 * @member {Number} studentId
 */
ReviewDTO.prototype.studentId = undefined;

