/*
 * Student Tutor Booking Management System
 * This is a system allowing students and tutors to book in-person sessions at designated venues on campus.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 222641495@mycput.ac.za
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The StudentDTO model module.
 * @module model/StudentDTO
 * @version 1.0.0
 */
export default class StudentDTO {
  /**
   * Constructs a new <code>StudentDTO</code>.
   * @alias module:model/StudentDTO
   * @class
   * @param name {String} 
   * @param lastName {String} 
   * @param email {String} 
   * @param phoneNumber {String} 
   * @param password {String} 
   * @param studentNumber {Number} 
   */
  constructor(name, lastName, email, phoneNumber, password, studentNumber) {
    this.name = name;
    this.lastName = lastName;
    this.email = email;
    this.phoneNumber = phoneNumber;
    this.password = password;
    this.studentNumber = studentNumber;
  }

  /**
   * Constructs a <code>StudentDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/StudentDTO} obj Optional instance to populate.
   * @return {module:model/StudentDTO} The populated <code>StudentDTO</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new StudentDTO();
      if (data.hasOwnProperty('studentId'))
        obj.studentId = ApiClient.convertToType(data['studentId'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('lastName'))
        obj.lastName = ApiClient.convertToType(data['lastName'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('phoneNumber'))
        obj.phoneNumber = ApiClient.convertToType(data['phoneNumber'], 'String');
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
      if (data.hasOwnProperty('studentNumber'))
        obj.studentNumber = ApiClient.convertToType(data['studentNumber'], 'Number');
      if (data.hasOwnProperty('profilePicture'))
        obj.profilePicture = ApiClient.convertToType(data['profilePicture'], 'Blob');
    }
    return obj;
  }
}

/**
 * @member {Number} studentId
 */
StudentDTO.prototype.studentId = undefined;

/**
 * @member {String} name
 */
StudentDTO.prototype.name = undefined;

/**
 * @member {String} lastName
 */
StudentDTO.prototype.lastName = undefined;

/**
 * @member {String} email
 */
StudentDTO.prototype.email = undefined;

/**
 * @member {String} phoneNumber
 */
StudentDTO.prototype.phoneNumber = undefined;

/**
 * @member {String} password
 */
StudentDTO.prototype.password = undefined;

/**
 * @member {Number} studentNumber
 */
StudentDTO.prototype.studentNumber = undefined;

/**
 * @member {Blob} profilePicture
 */
StudentDTO.prototype.profilePicture = undefined;

