/* tslint:disable */
/* eslint-disable */
/**
 * Student Tutor Booking Management System
 * This is a system allowing students and tutors to book in-person sessions at designated venues on campus.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 222641495@mycput.ac.za
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { BookingDTO } from '../models';
/**
 * BookingApi - axios parameter creator
 * @export
 */
export const BookingApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * This can only be done by the student.
         * @summary Create a new booking
         * @param {BookingDTO} body BookingDTO object that needs to be added to the system
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createBooking: async (body: BookingDTO, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling createBooking.');
            }
            const localVarPath = `/booking`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Deletes a booking
         * @summary Delete Booking by ID
         * @param {number} bookingId ID of booking to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteBooking: async (bookingId: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'bookingId' is not null or undefined
            if (bookingId === null || bookingId === undefined) {
                throw new RequiredError('bookingId','Required parameter bookingId was null or undefined when calling deleteBooking.');
            }
            const localVarPath = `/booking/{bookingId}`
                .replace(`{${"bookingId"}}`, encodeURIComponent(String(bookingId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns a single booking
         * @summary Get booking by ID
         * @param {number} bookingId ID of booking to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBookingById: async (bookingId: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'bookingId' is not null or undefined
            if (bookingId === null || bookingId === undefined) {
                throw new RequiredError('bookingId','Required parameter bookingId was null or undefined when calling getBookingById.');
            }
            const localVarPath = `/booking/{bookingId}`
                .replace(`{${"bookingId"}}`, encodeURIComponent(String(bookingId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * This can only be done by the student.
         * @summary Update a new booking
         * @param {BookingDTO} body BookingDTO object that needs to be updated on the system
         * @param {number} bookingId ID of booking to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateBooking: async (body: BookingDTO, bookingId: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling updateBooking.');
            }
            // verify required parameter 'bookingId' is not null or undefined
            if (bookingId === null || bookingId === undefined) {
                throw new RequiredError('bookingId','Required parameter bookingId was null or undefined when calling updateBooking.');
            }
            const localVarPath = `/booking/{bookingId}`
                .replace(`{${"bookingId"}}`, encodeURIComponent(String(bookingId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BookingApi - functional programming interface
 * @export
 */
export const BookingApiFp = function(configuration?: Configuration) {
    return {
        /**
         * This can only be done by the student.
         * @summary Create a new booking
         * @param {BookingDTO} body BookingDTO object that needs to be added to the system
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createBooking(body: BookingDTO, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<BookingDTO>>> {
            const localVarAxiosArgs = await BookingApiAxiosParamCreator(configuration).createBooking(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Deletes a booking
         * @summary Delete Booking by ID
         * @param {number} bookingId ID of booking to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteBooking(bookingId: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await BookingApiAxiosParamCreator(configuration).deleteBooking(bookingId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Returns a single booking
         * @summary Get booking by ID
         * @param {number} bookingId ID of booking to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getBookingById(bookingId: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<BookingDTO>>> {
            const localVarAxiosArgs = await BookingApiAxiosParamCreator(configuration).getBookingById(bookingId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * This can only be done by the student.
         * @summary Update a new booking
         * @param {BookingDTO} body BookingDTO object that needs to be updated on the system
         * @param {number} bookingId ID of booking to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateBooking(body: BookingDTO, bookingId: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<BookingDTO>>> {
            const localVarAxiosArgs = await BookingApiAxiosParamCreator(configuration).updateBooking(body, bookingId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * BookingApi - factory interface
 * @export
 */
export const BookingApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * This can only be done by the student.
         * @summary Create a new booking
         * @param {BookingDTO} body BookingDTO object that needs to be added to the system
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createBooking(body: BookingDTO, options?: AxiosRequestConfig): Promise<AxiosResponse<BookingDTO>> {
            return BookingApiFp(configuration).createBooking(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Deletes a booking
         * @summary Delete Booking by ID
         * @param {number} bookingId ID of booking to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteBooking(bookingId: number, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return BookingApiFp(configuration).deleteBooking(bookingId, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns a single booking
         * @summary Get booking by ID
         * @param {number} bookingId ID of booking to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getBookingById(bookingId: number, options?: AxiosRequestConfig): Promise<AxiosResponse<BookingDTO>> {
            return BookingApiFp(configuration).getBookingById(bookingId, options).then((request) => request(axios, basePath));
        },
        /**
         * This can only be done by the student.
         * @summary Update a new booking
         * @param {BookingDTO} body BookingDTO object that needs to be updated on the system
         * @param {number} bookingId ID of booking to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateBooking(body: BookingDTO, bookingId: number, options?: AxiosRequestConfig): Promise<AxiosResponse<BookingDTO>> {
            return BookingApiFp(configuration).updateBooking(body, bookingId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * BookingApi - object-oriented interface
 * @export
 * @class BookingApi
 * @extends {BaseAPI}
 */
export class BookingApi extends BaseAPI {
    /**
     * This can only be done by the student.
     * @summary Create a new booking
     * @param {BookingDTO} body BookingDTO object that needs to be added to the system
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BookingApi
     */
    public async createBooking(body: BookingDTO, options?: AxiosRequestConfig) : Promise<AxiosResponse<BookingDTO>> {
        return BookingApiFp(this.configuration).createBooking(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Deletes a booking
     * @summary Delete Booking by ID
     * @param {number} bookingId ID of booking to return
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BookingApi
     */
    public async deleteBooking(bookingId: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return BookingApiFp(this.configuration).deleteBooking(bookingId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Returns a single booking
     * @summary Get booking by ID
     * @param {number} bookingId ID of booking to return
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BookingApi
     */
    public async getBookingById(bookingId: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<BookingDTO>> {
        return BookingApiFp(this.configuration).getBookingById(bookingId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * This can only be done by the student.
     * @summary Update a new booking
     * @param {BookingDTO} body BookingDTO object that needs to be updated on the system
     * @param {number} bookingId ID of booking to return
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BookingApi
     */
    public async updateBooking(body: BookingDTO, bookingId: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<BookingDTO>> {
        return BookingApiFp(this.configuration).updateBooking(body, bookingId, options).then((request) => request(this.axios, this.basePath));
    }
}
