/*
 * Student Tutor Booking Management System
 * This is a system allowing students and tutors to book in-person sessions at designated venues on campus.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 222641495@mycput.ac.za
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.61
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The BookingDTO model module.
 * @module model/BookingDTO
 * @version 1.0.0
 */
export default class BookingDTO {
  /**
   * Constructs a new <code>BookingDTO</code>.
   * @alias module:model/BookingDTO
   * @class
   * @param tutorId {Number} 
   * @param studentId {Number} 
   * @param subjectId {Number} 
   * @param _date {Date} 
   * @param startTime {String} 
   * @param endTime {String} 
   * @param locationId {Number} 
   * @param topic {String} 
   */
  constructor(tutorId, studentId, subjectId, _date, startTime, endTime, locationId, topic) {
    this.tutorId = tutorId;
    this.studentId = studentId;
    this.subjectId = subjectId;
    this._date = _date;
    this.startTime = startTime;
    this.endTime = endTime;
    this.locationId = locationId;
    this.topic = topic;
  }

  /**
   * Constructs a <code>BookingDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BookingDTO} obj Optional instance to populate.
   * @return {module:model/BookingDTO} The populated <code>BookingDTO</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new BookingDTO();
      if (data.hasOwnProperty('bookingId'))
        obj.bookingId = ApiClient.convertToType(data['bookingId'], 'Number');
      if (data.hasOwnProperty('tutorId'))
        obj.tutorId = ApiClient.convertToType(data['tutorId'], 'Number');
      if (data.hasOwnProperty('studentId'))
        obj.studentId = ApiClient.convertToType(data['studentId'], 'Number');
      if (data.hasOwnProperty('subjectId'))
        obj.subjectId = ApiClient.convertToType(data['subjectId'], 'Number');
      if (data.hasOwnProperty('date'))
        obj._date = ApiClient.convertToType(data['date'], 'Date');
      if (data.hasOwnProperty('startTime'))
        obj.startTime = ApiClient.convertToType(data['startTime'], 'String');
      if (data.hasOwnProperty('endTime'))
        obj.endTime = ApiClient.convertToType(data['endTime'], 'String');
      if (data.hasOwnProperty('locationId'))
        obj.locationId = ApiClient.convertToType(data['locationId'], 'Number');
      if (data.hasOwnProperty('topic'))
        obj.topic = ApiClient.convertToType(data['topic'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} bookingId
 */
BookingDTO.prototype.bookingId = undefined;

/**
 * @member {Number} tutorId
 */
BookingDTO.prototype.tutorId = undefined;

/**
 * @member {Number} studentId
 */
BookingDTO.prototype.studentId = undefined;

/**
 * @member {Number} subjectId
 */
BookingDTO.prototype.subjectId = undefined;

/**
 * @member {Date} _date
 */
BookingDTO.prototype._date = undefined;

/**
 * @member {String} startTime
 */
BookingDTO.prototype.startTime = undefined;

/**
 * @member {String} endTime
 */
BookingDTO.prototype.endTime = undefined;

/**
 * @member {Number} locationId
 */
BookingDTO.prototype.locationId = undefined;

/**
 * @member {String} topic
 */
BookingDTO.prototype.topic = undefined;

