/*
 * Student Tutor Booking Management System
 * This is a system allowing students and tutors to book in-person sessions at designated venues on campus.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 222641495@mycput.ac.za
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.61
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The LocationDTO model module.
 * @module model/LocationDTO
 * @version 1.0.0
 */
export default class LocationDTO {
  /**
   * Constructs a new <code>LocationDTO</code>.
   * @alias module:model/LocationDTO
   * @class
   * @param room {String} 
   * @param building {String} 
   */
  constructor(room, building) {
    this.room = room;
    this.building = building;
  }

  /**
   * Constructs a <code>LocationDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LocationDTO} obj Optional instance to populate.
   * @return {module:model/LocationDTO} The populated <code>LocationDTO</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new LocationDTO();
      if (data.hasOwnProperty('locationId'))
        obj.locationId = ApiClient.convertToType(data['locationId'], 'Number');
      if (data.hasOwnProperty('room'))
        obj.room = ApiClient.convertToType(data['room'], 'String');
      if (data.hasOwnProperty('building'))
        obj.building = ApiClient.convertToType(data['building'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} locationId
 */
LocationDTO.prototype.locationId = undefined;

/**
 * @member {String} room
 */
LocationDTO.prototype.room = undefined;

/**
 * @member {String} building
 */
LocationDTO.prototype.building = undefined;

