/*
 * Student Tutor Booking Management System
 * This is a system allowing students and tutors to book in-person sessions at designated venues on campus.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 222641495@mycput.ac.za
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.61
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The SubjectDTO model module.
 * @module model/SubjectDTO
 * @version 1.0.0
 */
export default class SubjectDTO {
  /**
   * Constructs a new <code>SubjectDTO</code>.
   * @alias module:model/SubjectDTO
   * @class
   * @param subjectCode {String} 
   * @param subjectName {String} 
   */
  constructor(subjectCode, subjectName) {
    this.subjectCode = subjectCode;
    this.subjectName = subjectName;
  }

  /**
   * Constructs a <code>SubjectDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SubjectDTO} obj Optional instance to populate.
   * @return {module:model/SubjectDTO} The populated <code>SubjectDTO</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SubjectDTO();
      if (data.hasOwnProperty('subjectId'))
        obj.subjectId = ApiClient.convertToType(data['subjectId'], 'Number');
      if (data.hasOwnProperty('subjectCode'))
        obj.subjectCode = ApiClient.convertToType(data['subjectCode'], 'String');
      if (data.hasOwnProperty('subjectName'))
        obj.subjectName = ApiClient.convertToType(data['subjectName'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} subjectId
 */
SubjectDTO.prototype.subjectId = undefined;

/**
 * @member {String} subjectCode
 */
SubjectDTO.prototype.subjectCode = undefined;

/**
 * @member {String} subjectName
 */
SubjectDTO.prototype.subjectName = undefined;

