/*
 * Student Tutor Booking Management System
 * This is a system allowing students and tutors to book in-person sessions at designated venues on campus.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 222641495@mycput.ac.za
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.61
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The UserDTO model module.
 * @module model/UserDTO
 * @version 1.0.0
 */
export default class UserDTO {
  /**
   * Constructs a new <code>UserDTO</code>.
   * @alias module:model/UserDTO
   * @class
   * @param name {String} 
   * @param lastName {String} 
   * @param email {String} 
   * @param phoneNumber {String} 
   * @param password {String} 
   * @param role {module:model/UserDTO.RoleEnum} 
   */
  constructor(name, lastName, email, phoneNumber, password, role) {
    this.name = name;
    this.lastName = lastName;
    this.email = email;
    this.phoneNumber = phoneNumber;
    this.password = password;
    this.role = role;
  }

  /**
   * Constructs a <code>UserDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserDTO} obj Optional instance to populate.
   * @return {module:model/UserDTO} The populated <code>UserDTO</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UserDTO();
      if (data.hasOwnProperty('userId'))
        obj.userId = ApiClient.convertToType(data['userId'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('lastName'))
        obj.lastName = ApiClient.convertToType(data['lastName'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('phoneNumber'))
        obj.phoneNumber = ApiClient.convertToType(data['phoneNumber'], 'String');
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
      if (data.hasOwnProperty('role'))
        obj.role = ApiClient.convertToType(data['role'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} userId
 */
UserDTO.prototype.userId = undefined;

/**
 * @member {String} name
 */
UserDTO.prototype.name = undefined;

/**
 * @member {String} lastName
 */
UserDTO.prototype.lastName = undefined;

/**
 * @member {String} email
 */
UserDTO.prototype.email = undefined;

/**
 * @member {String} phoneNumber
 */
UserDTO.prototype.phoneNumber = undefined;

/**
 * @member {String} password
 */
UserDTO.prototype.password = undefined;

/**
 * Allowed values for the <code>role</code> property.
 * @enum {String}
 * @readonly
 */
UserDTO.RoleEnum = {
  /**
   * value: "Student"
   * @const
   */
  student: "Student",

  /**
   * value: "Tutor"
   * @const
   */
  tutor: "Tutor",

  /**
   * value: "Admin"
   * @const
   */
  admin: "Admin"
};
/**
 * @member {module:model/UserDTO.RoleEnum} role
 */
UserDTO.prototype.role = undefined;

