/* tslint:disable */
/* eslint-disable */
/**
 * Student Tutor Booking Management System
 * This is a system allowing students and tutors to book in-person sessions at designated venues on campus.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 222641495@mycput.ac.za
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UserDTO
 */
export interface UserDTO {

    /**
     * @type {number}
     * @memberof UserDTO
     */
    userId?: number;

    /**
     * @type {string}
     * @memberof UserDTO
     */
    name: string;

    /**
     * @type {string}
     * @memberof UserDTO
     */
    lastName: string;

    /**
     * @type {string}
     * @memberof UserDTO
     */
    email: string;

    /**
     * @type {string}
     * @memberof UserDTO
     */
    phoneNumber: string;

    /**
     * @type {string}
     * @memberof UserDTO
     */
    password: string;

    /**
     * @type {string}
     * @memberof UserDTO
     */
    role: UserDTORoleEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum UserDTORoleEnum {
    Student = 'Student',
    Tutor = 'Tutor',
    Admin = 'Admin'
}

